// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion() {
  return window['go']['backend']['App']['GetAppVersion']();
}

export function GetPendingFile() {
  return window['go']['backend']['App']['GetPendingFile']();
}

export function GetRelativePath(arg1, arg2) {
  return window['go']['backend']['App']['GetRelativePath'](arg1, arg2);
}

export function HtmlToMd(arg1) {
  return window['go']['backend']['App']['HtmlToMd'](arg1);
}

export function HtmlToMdForFile(arg1, arg2) {
  return window['go']['backend']['App']['HtmlToMdForFile'](arg1, arg2);
}

export function LoadConfig() {
  return window['go']['backend']['App']['LoadConfig']();
}

export function LoadTranslations(arg1) {
  return window['go']['backend']['App']['LoadTranslations'](arg1);
}

export function MdToHtml(arg1) {
  return window['go']['backend']['App']['MdToHtml'](arg1);
}

export function MdToHtmlWithBase(arg1, arg2) {
  return window['go']['backend']['App']['MdToHtmlWithBase'](arg1, arg2);
}

export function NewWindow(arg1) {
  return window['go']['backend']['App']['NewWindow'](arg1);
}

export function OnFileOpen(arg1) {
  return window['go']['backend']['App']['OnFileOpen'](arg1);
}

export function OpenFileDialog() {
  return window['go']['backend']['App']['OpenFileDialog']();
}

export function ReadFile(arg1) {
  return window['go']['backend']['App']['ReadFile'](arg1);
}

export function ResolveImagePath(arg1, arg2) {
  return window['go']['backend']['App']['ResolveImagePath'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['backend']['App']['SaveConfig'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['backend']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileDialog() {
  return window['go']['backend']['App']['SaveFileDialog']();
}

export function SetDirty(arg1) {
  return window['go']['backend']['App']['SetDirty'](arg1);
}

export function UnresolveImagePath(arg1) {
  return window['go']['backend']['App']['UnresolveImagePath'](arg1);
}
