// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion() {
  return window['go']['backend']['App']['GetAppVersion']();
}

export function HtmlToMd(arg1) {
  return window['go']['backend']['App']['HtmlToMd'](arg1);
}

export function HtmlToMdForFile(arg1, arg2) {
  return window['go']['backend']['App']['HtmlToMdForFile'](arg1, arg2);
}

export function LoadConfig() {
  return window['go']['backend']['App']['LoadConfig']();
}

export function LoadTranslations(arg1) {
  return window['go']['backend']['App']['LoadTranslations'](arg1);
}

export function MdToHtml(arg1) {
  return window['go']['backend']['App']['MdToHtml'](arg1);
}

export function MdToHtmlWithBase(arg1, arg2) {
  return window['go']['backend']['App']['MdToHtmlWithBase'](arg1, arg2);
}

export function OpenFileDialog() {
  return window['go']['backend']['App']['OpenFileDialog']();
}

export function ReadFile(arg1) {
  return window['go']['backend']['App']['ReadFile'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['backend']['App']['SaveConfig'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['backend']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileDialog() {
  return window['go']['backend']['App']['SaveFileDialog']();
}
